### ISSUE TITLE
Camp-Icons werden in den Widgets auf der mobilen Plattform nicht angezeigt

### ISSUE THREAD

**Issue by dj95** [Linux-statt-Windows/NodeBB#1]
Statt der Icons wird nur der Titel in den Buttons der Widgets der einzelnen Camps angezeigt.

Getestet mit  Chrome unter Android 6 und Safari in iOS 9.1.

**Comment by rbeer** [comment]
Habe da vorgestern 'was anderes gehoert. Existiert der Fehler noch?

**Comment by dj95** [comment]
Ist anscheinend gelöst

![image](https://cloud.githubusercontent.com/assets/4348959/11113322/329facd6-891c-11e5-80d9-962be5aa6527.png)
