### ISSUE TITLE
Link zu Homepage in Profil "kaputt"

### ISSUE THREAD

**Issue by DaGuich** [Linux-statt-Windows/NodeBB#3]
Die Links zu der Homepage eines Users in dessen Profil werden maskiert
Beispiel: https://linux-statt-windows.org/user/dj-95 
Link: `http:&#x2F;&#x2F;daniel-jankowski.net`

**Comment by rbeer** [comment]
Hi @DaGuich
Wie es aussieht speichert die neue Version Profilfelder nicht mehr escaped.

#### quick fix

Die HTML entities (`&#x2F; -> /`, `&amp; -> &`, <a href="http://dev.w3.org/html5/html-author/charref" target="_blank">usw</a>) per Hand aendern und das Profil speichern. Von dem Fehler sind alle Felder betroffen.

#### solution

9c7af5f wird morgen ueberprueft.

Vielen Dank fuer's melden :)

**Comment by dj95** [comment]
cleanup/inactivity
